name: Scrape All

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Get previous run ID
        id: get_run_id
        run: |
          RUN_ID=$(curl --silent --show-error -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/actions/workflows/continuousScrape.yaml/runs" \
            | jq '.workflow_runs[1].id')
          echo "Previous run ID: $RUN_ID"
          echo "::set-output name=run_id::$RUN_ID"

      - name: Download Artifacts from Last Workflow
        uses: actions/download-artifact@v4
        with:
          name: db
          path: db
          github-token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          # Previous run ID
          run-id: ${{ steps.get_run_id.outputs.run_id }}
        continue-on-error: true

      - name: Install Dependencies
        run: npm ci

      - name: Create db/pixiv.db if it doesn't exist
        run: |
          if [ ! -f db/pixiv.db ]; then
            npx prisma migrate dev
          fi

      - name: Set up DB
        run: npm run migrate

      - name: Build
        run: npm run build

      - name: Scrape
        # 5.9 hours
        # run: node . --timeout=
        run: node . --timeout=5000

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: db
          path: db/*
